[package]
name = "elf-calibration"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
regex = "1.10.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html